GeoAgenda/GeoAgenda/Models/Conductor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GeoAgenda.Models
{
    [Table("Conductores")]
    public class Conductor
    {
        [Key]
        public int IdConductor { get; set; }
        public string Nombre { get; set; }
        public string NroRegistro { get; set; }

        [DataType(DataType.ImageUrl)]
        public string Foto { get; set; }

        public virtual ICollection<Entrega> entrega { get; set; }


    }
}

GeoAgenda/GeoAgenda/Models/ConductorView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GeoAgenda.Models
{
    public class ConductorView
    {
        public int IdConductor { get; set; }
        public string Nombre { get; set; }
        public string NroRegistro { get; set; }

        [DataType(DataType.ImageUrl)]
        public HttpPostedFileBase Foto { get; set; }


        public virtual ICollection<Entrega> entrega { get; set; }
    }
}

GeoAgenda/GeoAgenda/Controllers/ConductorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GeoAgenda.Context;
using GeoAgenda.Models;
using System.IO;

namespace GeoAgenda.Controllers
{
    public class ConductorController : Controller
    {
        private GeoAgendaContext db = new GeoAgendaContext();

        // GET: Conductor
        public ActionResult Index()
        {
            return View(db.Conductores.ToList());
        }

        // GET: Conductor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Conductor conductor = db.Conductores.Find(id);
            if (conductor == null)
            {
                return HttpNotFound();
            }
            return View(conductor);
        }

        // GET: Conductor/Create
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ConductorView conductorview)
        {
            if (ModelState.IsValid)
            {
                string path = string.Empty;
                string imag = string.Empty;

                if (conductorview.Foto != null)
                {
                    imag = Path.GetFileName(conductorview.Foto.FileName);
                    path = Path.Combine(Server.MapPath("~/Content/Fotos"), imag);
                    conductorview.Foto.SaveAs(path);

                    using (MemoryStream ms = new MemoryStream())
                    {
                        conductorview.Foto.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }

                }

                var conductor = new Conductor
                {
                    Nombre = conductorview.Nombre,
                    NroRegistro = conductorview.NroRegistro,
                    entrega = conductorview.entrega,

                    Foto = imag == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}", imag),

                };

                try
                {
                    db.Conductores.Add(conductor);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {


                }
            }

            return View(conductorview);
        }

        // GET: Conductor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Conductor conductor = db.Conductores.Find(id);
            if (conductor == null)
            {
                return HttpNotFound();
            }
            return View(conductor);
        }

        // POST: Conductor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Conductor conductor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(conductor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(conductor);
        }

        // GET: Conductor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Conductor conductor = db.Conductores.Find(id);
            if (conductor == null)
            {
                return HttpNotFound();
            }
            return View(conductor);
        }

        // POST: Conductor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Conductor conductor = db.Conductores.Find(id);
            db.Conductores.Remove(conductor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GeoAgenda/GeoAgenda/Views/Conductor/Create.cshtml
@model GeoAgenda.Models.ConductorView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Conductor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Conductor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NroRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NroRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NroRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-defaul btn-file">
                    @Html.TextBoxFor(model => model.Foto, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GeoAgenda/GeoAgenda/Views/Conductor/Delete.cshtml
@model GeoAgenda.Models.Conductor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Conductor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NroRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NroRegistro)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GeoAgenda/GeoAgenda/Views/Conductor/Details.cshtml
@model GeoAgenda.Models.Conductor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Conductor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NroRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NroRegistro)
        </dd>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Foto))
            {
                <img src="@Url.Content(Model.Foto)" alt="Image" style="width:200px;height:200px; max-width:100%;height:auto" />
            }

        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdConductor }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GeoAgenda/GeoAgenda/Views/Conductor/Edit.cshtml
@model GeoAgenda.Models.Conductor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Conductor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdConductor)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NroRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NroRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NroRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GeoAgenda/GeoAgenda/Views/Conductor/Index.cshtml
@model IEnumerable<GeoAgenda.Models.Conductor>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NroRegistro)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NroRegistro)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdConductor }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdConductor }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdConductor })
        </td>
    </tr>
}

</table>